### PR TITLE
Fix number of items in the cart

### PR DESCRIPTION
**Pull request by tominon**

### CODE REVIEW

**Comment by bomshteyn** [comment]
Hi @tominon , thanks for your pull requests would you mind adding a brief explanation of what this change fixes / changes and why? Having a brief explanation makes it much easier to review the commits.

**Comment by avrahamappel** [comment]
Hi @tominon, that's a good idea to have a sum of the quantity, but can you add it as a separate method? I'd prefer to leave the `count` method the way it is. Thanks!

**Comment by tominon** [comment]
IMHO, `count()` method should return total number of items in the cart. So if you've added 3 cups and 1 teaspoon, it should return 4 items.

**Comment by avrahamappel** [comment]
I hear you. @bomshteyn likes it too.

**Pull request merged**
